#!/bin/sh

# The name (YYYYMMDDhhmm) of the Couchbase backup is passed on the command
# line. This is then restored from  /backup/<YYYYMMDDhhmm>/ inside the Docker
# container

SNAPSHOT=$1

# The value of COUCHBASE_ADMIN_PASSWORD is retrieved.
COUCHBASE_ADMIN_PASSWORD=$(cat ./cbap)

CONTAINER=`sudo docker ps -q`

restore ()
{
    sudo docker exec $CONTAINER cbrestore  /backup/$SNAPSHOT \
    -u admin -p $COUCHBASE_ADMIN_PASSWORD http://172.17.0.2:8091 \
    --bucket-source=$1 --bucket-destination=$1
}

restore 'default'
restore 'openmoney_global'
restore 'oauth2Server'
restore 'openmoney_stewards'
