#!/bin/sh
# couchbase_backup <couchbase admin password>
# Last modified: 2020/03/16 20.40 John Waters

# Assumptions:
# (1) The OM instance has a VM (almost) to itself.
# (2) The primary non-root user is "om" and has passwordless sudo access.
# (3) The usr "om" is able to run the sudo commands below without a password.
# (4) The directory /home/om/backup/ has already been created.
# (5) The directory /backup/ has already been created inside Couchbases's
#     Docker container.
# (6) Couchbase's Docker container is the only one running inside this VM.

CONTAINER=`sudo docker ps -q`

# The backup file directory is named with the date-/time-string:
DATESTRING=`date +%Y%m%d%H%M`

# The Couchbase admin password assigned by /home/om/openmoney-api/install.sh
# and saved in both  
#   /home/om/openmoney-api/.env
# and
#   /home/om/openmoney-api/docker-scripts/cbap

# Retrieve from value generated and saved during initial installation
COUCHBASE_ADMIN_PASSWORD=$(cat /home/om/docker-scripts/cbap)

sudo docker exec $CONTAINER cbbackup -u admin -p $COUCHBASE_ADMIN_PASSWORD \
  http://172.17.0.2:8091 /backup/$DATESTRING

# The DB backup is then tarballed ...
sudo docker exec $CONTAINER tar zcf cbdata$DATESTRING.tar.gz /backup/$DATESTRING
# ... and copied to the local backups directory
sudo docker cp $CONTAINER:cbdata$DATESTRING.tar.gz /home/om/backups/
sudo docker exec $CONTAINER rm cbdata$DATESTRING.tar.gz

sudo chown -R om:om /home/om/backups
